language: generic
install:
- source ./texlive/texlive_install.sh
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
before_script: cd $TRAVIS_BUILD_DIR/
script:
- texliveonfly revision-guide.tex
- latexmk -pdf revision-guide.tex
deploy:
  provider: releases
  api_key:
    secure: cVp+iU9vaRXCVU5YcukybAJK6D1TcSuYOiT3Zu594XA1IPg9n/vzS857Dn90AmnTd9ME3/hl2T51i479GB/dI7lDNnMN3fC0eEqas3pM/7xVClqwYbpPJSHH0YR5hCKGCifUJBzrZnMZSmC6a0r9kaJJmoAcdcSS7RnfNJIhUMSwAiWXQlFt8lMts0NXncUBO7mkPWTt/r9Kve+UAc4kO3XEJpGdyMfpt7WZwfPHZorg3WUpuAt9UD1M4DCQtqQMv+5U7EpRigpleTCGVV/8wXepRNgV/IJjmbZ2hzRZG+gBDGNCvr8RzKuIvxtlQ10C0jr2DZNfd21il7OrCA7uE7L892WMpUU34YruM672cLgUyArcUo7LBlLMYd4WhI3Pi507UpzlZpdotcULbQOo+om7cKQ71wXe3gqBkPVV8raPlFhx4HzNyPCDH7ex+uDUzelPPKLPRwz3P0u5LvyG3//wernBKp6bS42AJRRVtww4V9GaFUyHMR7dp4/36ORLVO/9DqLHTcfE4KjpthNGISSxCRNCSocIqYflO2EM8/9NvykoHER9Dr3a/loL+QamPxygnI7POA3f4T+/sP0ojSOJ9ZvtXk7Xih312O9H9W1nySL7ORKQXtsV4EmnxedPp9c6Pel8Z1XyFx2KPakpQn2AcmOevvzBECMH8jvsTtI=
  file: revision-guide.pdf
  skip_cleanup: true
  draft: true
  on:
    repo: mrpsharp/physics-PreU
